# Generated by Django 3.2 on 2022-08-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs97test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstest',
            old_name='long',
            new_name='lng',
        ),
    ]
