# Generated by Django 3.2 on 2022-08-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs97test', '0002_rename_long_jobstest_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('total_star', models.FloatField()),
                ('star', models.FloatField()),
                ('summary', models.CharField(max_length=500)),
                ('good', models.CharField(max_length=500)),
                ('bad', models.CharField(max_length=500)),
            ],
        ),
    ]
